In [1]:
import pandas as pd
import numpy as np
import math as math
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df_house = pd.read_csv('../housing_conditions_ownership.csv')
df_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 54 columns):
hh_ids                           301 non-null object
hh_int_situation                 295 non-null object
hh_circ_move_why                 288 non-null object
hh_circ_move_when                291 non-null object
hh_circ_problems                 292 non-null object
hh_inf_wall_material             293 non-null object
hh_inf_roof_material             293 non-null object
hh_inf_floor_material            294 non-null object
hh_inf_cookfuel_source           298 non-null object
hh_inf_lighting_source           294 non-null object
hh_inf_water_source              297 non-null object
hh_inf_rooms_habitable           296 non-null float64
hh_inf_rooms_other               296 non-null float64
hh_inf_toilet_type               296 non-null object
hh_inf_toilet_shared             286 non-null object
hh_inf_housing_type              292 non-null object
hh_inf_electricity_access        286 non-null object
hh_inf_interiorcond              283 non-null object
hh_inf_exteriorcond              282 non-null object
hh_asset_internet_access         295 non-null object
hh_asset_iron_any                294 non-null object
hh_asset_mosqnets_N              295 non-null float64
hh_asset_towels_N                296 non-null float64
hh_asset_fryingpan_N             294 non-null float64
hh_env_settingdesc               294 non-null object
hh_env_desc                      280 non-null object
hh_env_dilapbuildings            281 non-null object
hh_env_streets                   269 non-null object
hh_env_trash                     277 non-null object
hh_ownership_type                295 non-null float64
hh_ownership_plotacquisition     180 non-null object
hh_ownership_houseacquisition    172 non-null object
hh_ownership_docu                183 non-null object
hh_otherprop_any                 295 non-null object
hh_otherprop_N                   82 non-null float64
hh_otherprop1_docu               76 non-null object
hh_otherprop1_use                75 non-null object
hh_otherprop1_value              73 non-null float64
hh_otherprop2_use                7 non-null object
hh_otherprop2_value              6 non-null float64
hh_otherprop2_docu               7 non-null object
hh_otherprop3_docu               1 non-null object
hh_otherprop3_use                1 non-null object
hh_otherprop3_value              1 non-null float64
hh_othershamba_N                 45 non-null float64
hh_othershamba1_docu             38 non-null object
hh_othershamba1_use              38 non-null object
hh_othershamba1_value            37 non-null float64
hh_othershamba2_docu             6 non-null object
hh_othershamba2_use              6 non-null object
hh_othershamba2_value            6 non-null float64
hh_othershamba3_docu             2 non-null object
hh_othershamba3_use              2 non-null object
hh_othershamba3_value            2 non-null float64
dtypes: float64(14), object(40)
memory usage: 127.1+ KB

In [4]:
df_house.head()

,hh_ids,hh_int_situation,hh_circ_move_why,hh_circ_move_when,hh_circ_problems,hh_inf_wall_material,hh_inf_roof_material,hh_inf_floor_material,hh_inf_cookfuel_source,hh_inf_lighting_source,...,hh_othershamba_N,hh_othershamba1_docu,hh_othershamba1_use,hh_othershamba1_value,hh_othershamba2_docu,hh_othershamba2_use,hh_othershamba2_value,hh_othershamba3_docu,hh_othershamba3_use,hh_othershamba3_value
0,KNBOK31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KNBOK01,01=Initial questionnaire,05=To be closer to family,7/1/1997,"01=Leaky roof or ceilling,04=Pests: mice, rats...",Stone,"Corrugated iron, mabati",Cement/Concrete/Slab,Paraffin,Paraffin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,KNBOK02,01=Initial questionnaire,12=Wanted better neighborhood,2/1/2011,01=Leaky roof or ceilling,Stone,"Corrugated iron, mabati",Cement/Concrete/Slab,Paraffin,Electricity,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KNBOK04,01=Initial questionnaire,17=Private displacement (owner moved into unit...,2/19/2006,"03=Broken or missing windows,07=Extremely hot ...",Stone,Concrete,Cement/Concrete/Slab,Gas/LPG,Electricity,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,KNBOK05,01=Initial questionnaire,13=Change from renter to owner,1/1/1993,"07=Extremely hot or cold,08=Mold",Corrugated Iron Sheet,"Corrugated iron, mabati",Cement/Concrete/Slab,Collected firewood,Electricity,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_house.columns

Index(['hh_ids', 'hh_int_situation', 'hh_circ_move_why', 'hh_circ_move_when',
       'hh_circ_problems', 'hh_inf_wall_material', 'hh_inf_roof_material',
       'hh_inf_floor_material', 'hh_inf_cookfuel_source',
       'hh_inf_lighting_source', 'hh_inf_water_source',
       'hh_inf_rooms_habitable', 'hh_inf_rooms_other', 'hh_inf_toilet_type',
       'hh_inf_toilet_shared', 'hh_inf_housing_type',
       'hh_inf_electricity_access', 'hh_inf_interiorcond',
       'hh_inf_exteriorcond', 'hh_asset_internet_access', 'hh_asset_iron_any',
       'hh_asset_mosqnets_N', 'hh_asset_towels_N', 'hh_asset_fryingpan_N',
       'hh_env_settingdesc', 'hh_env_desc', 'hh_env_dilapbuildings',
       'hh_env_streets', 'hh_env_trash', 'hh_ownership_type',
       'hh_ownership_plotacquisition', 'hh_ownership_houseacquisition',
       'hh_ownership_docu', 'hh_otherprop_any', 'hh_otherprop_N',
       'hh_otherprop1_docu', 'hh_otherprop1_use', 'hh_otherprop1_value',
       'hh_otherprop2_use', 'hh_otherprop2_value', 'hh_otherprop2_docu',
       'hh_otherprop3_docu', 'hh_otherprop3_use', 'hh_otherprop3_value',
       'hh_othershamba_N', 'hh_othershamba1_docu', 'hh_othershamba1_use',
       'hh_othershamba1_value', 'hh_othershamba2_docu', 'hh_othershamba2_use',
       'hh_othershamba2_value', 'hh_othershamba3_docu', 'hh_othershamba3_use',
       'hh_othershamba3_value'],
      dtype='object')

In [6]:
df_house.sample(3)

,hh_ids,hh_int_situation,hh_circ_move_why,hh_circ_move_when,hh_circ_problems,hh_inf_wall_material,hh_inf_roof_material,hh_inf_floor_material,hh_inf_cookfuel_source,hh_inf_lighting_source,...,hh_othershamba_N,hh_othershamba1_docu,hh_othershamba1_use,hh_othershamba1_value,hh_othershamba2_docu,hh_othershamba2_use,hh_othershamba2_value,hh_othershamba3_docu,hh_othershamba3_use,hh_othershamba3_value
290,KVIHK33,01=Initial questionnaire,15=Needed larger house or apartment,7/28/1997,09=None,Brick/block,"Corrugated iron, mabati",Cement/Concrete/Slab,Collected firewood,Paraffin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,KVIHC06,01=Initial questionnaire,08=Seeking better business opportunities,7/1/2011,"04=Pests: mice, rats, roaches, bedbugs, other ...",Brick/block,"Corrugated iron, mabati",Cement/Concrete/Slab,Charcoal,Electricity,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,KMAKL40,01=Initial questionnaire,03=Started own household,8/1/2004,09=None,Brick/block,"Corrugated iron, mabati",Cement/Concrete/Slab,Purchased firewood,Paraffin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_house.describe()

,hh_inf_rooms_habitable,hh_inf_rooms_other,hh_asset_mosqnets_N,hh_asset_towels_N,hh_asset_fryingpan_N,hh_ownership_type,hh_otherprop_N,hh_otherprop1_value,hh_otherprop2_value,hh_otherprop3_value,hh_othershamba_N,hh_othershamba1_value,hh_othershamba2_value,hh_othershamba3_value
count,296.000000,296.000000,295.000000,296.000000,294.000000,295.000000,82.000000,7.300000e+01,6.000000,1.0,45.000000,3.700000e+01,6.000000e+00,2.000000
mean,2.486486,1.425676,2.196610,1.510135,0.755102,2.149153,1.085366,5.939479e+05,191666.666667,100000.0,0.888889,4.850541e+05,4.533333e+05,301750.000000
std,1.345357,1.491632,1.888559,1.667201,0.793247,1.479379,0.612649,1.899143e+06,80104.098938,NaN,0.745356,5.083028e+05,5.394689e+05,421789.194978
min,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,9.900000e+01,100000.000000,100000.0,0.000000,7.000000e+03,1.000000e+04,3500.000000
25%,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,5.000000e+04,125000.000000,100000.0,0.000000,1.000000e+05,1.525000e+05,152625.000000
50%,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+05,200000.000000,100000.0,1.000000,3.000000e+05,1.800000e+05,301750.000000
75%,3.000000,2.000000,3.000000,2.000000,1.000000,4.000000,1.000000,3.750000e+05,237500.000000,100000.0,1.000000,7.000000e+05,6.500000e+05,450875.000000
max,8.000000,21.000000,10.000000,14.000000,6.000000,6.000000,5.000000,1.500000e+07,300000.000000,100000.0,4.000000,2.000000e+06,1.400000e+06,600000.000000

In [9]:
df_house.shape

(301, 54)

In [10]:
df_house['hh_inf_rooms_habitable'].mean()

2.4864864864864864

In [11]:
df_house['hh_inf_rooms_other'].mean()

1.4256756756756757