In [5]:
import pandas as pd
import numpy as np
import math as math
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [6]:
def conv(val):
    if val == np.nan:
        return 0
    return val

In [7]:
df = pd.read_csv("../../rem_ind_over_trx_yr_mo_kes.csv")

In [8]:
df.head()

,hh_ids,m_ids_owner,rem_i_unique_sources,rem_i_meanptrx,rem_i_sdptrx,rem_i_meanptrx_RG,rem_i_sdptrx_RG,rem_i_meanptrx_RR,rem_i_sdptrx_RR,rem_i_count_medianpti,...,rem_i_net_medianpti_cash,rem_i_count_medianpti_inkind,rem_i_abs_medianpti_inkind,rem_i_net_medianpti_inkind,rem_i_count_medianpti_mm,rem_i_abs_medianpti_mm,rem_i_net_medianpti_mm,rem_i_count_medianpti_other,rem_i_abs_medianpti_other,rem_i_net_medianpti_other
0,KELDK02,56134389503000000,1,4606.4210,2317.3330,4606.421,2317.333,NaN,NaN,2.0,...,-3135.0,0.0,0.0,0.0,1.0,2500.0,-2500.0,0.0,0,0
1,KELDK08,56134410709700000,2,428.5000,139.3000,NaN,NaN,330.0000,NaN,1.0,...,0.0,0.0,0.0,0.0,1.0,428.5,-98.5,0.0,0,0
2,KELDK09,56134329944600000,5,656.1765,1560.7240,5000.000,1732.051,NaN,NaN,2.0,...,0.0,2.0,300.0,30.0,0.0,0.0,0.0,0.0,0,0
3,KELDK10,56134337157200000,6,166.8349,618.0686,NaN,NaN,114.8535,503.7492,29.0,...,-100.0,27.0,950.0,570.0,0.0,0.0,0.0,0.0,0,0
4,KELDK12,65134436228800000,1,2000.0000,NaN,2000.000,NaN,NaN,NaN,1.0,...,-2000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0