In [1]:
import pandas as pd
import numpy as np
import math as math
import matplotlib.pyplot as plt
import seaborn as sns
import random
%matplotlib inline

In [3]:
df = pd.read_csv("../../diaries_transactions_all.csv", dtype={'account_startclose_balance': str})

In [4]:
dfb = df[(df["trx_family_code"]=="FRMLN")&((df["trx_type_code"]==2760)|(df["trx_type_code"]==3247))]

In [8]:
dfb["trx_prx_purpose"].unique()

array(['6. Closing Balance--End of last DQ',
       '1. Starting balance (today)', '5. Interest accruing',
       '3. Payments', 'INCREASE--Unexplained balance adjustment',
       '2. New borrowinng (individual portion)', '4. Any known fees',
       'DECREASE--Unexplained balance adjustment',
       '7. Refund from lender', '2. New borrowing'], dtype=object)

In [9]:
for acc in dfb["account_ids"].unique():
    u = 0
    for index,row in dfb[dfb["account_ids"]==acc].iterrows():
        if row["trx_prx_purpose"]=="DECREASE--Unexplained balance adjustment" or row["trx_prx_purpose"]=="INCREASE--Unexplained balance adjustment":
            u = 1
    for index,row in dfb[dfb["account_ids"]==acc].iterrows():
        dfb.at[index,"acc_unexplained_trx"] = u

In [10]:
s = set()
for acc in dfb[dfb["acc_unexplained_trx"]==0]["account_ids"].unique():
     for i in dfb[dfb["account_ids"]==acc]["trx_prx_purpose"].unique():
            s.add(i)
print(s)

{'4. Any known fees', '2. New borrowinng (individual portion)', '7. Refund from lender', '2. New borrowing', '1. Starting balance (today)', '6. Closing Balance--End of last DQ', '5. Interest accruing', '3. Payments'}

In [11]:
dfb = dfb[dfb["acc_unexplained_trx"]==0]

In [27]:
del dfb["new_account_ids"]
dfb.insert(df.columns.get_loc("account_ids")+1,"new_account_ids", ["-"]*(dfb.shape[0]))
dfb.sample(1)

,hh_ids,unique_hhs,first_trx_date_hh,last_trx_date_hh,tot_hh_daysofobs,tot_hh_monthsofobs,interview_designation,int_date,int_month,int_year,...,trx_outlet,trx_direction,trx_value_kes,trx_value_usd,ddd_gift,trx_inkind_units,trx_inkind_value_usd,trx_inkind_value_kes,trx_stdtime_mnths_hh_nr,acc_unexplained_trx
288513,KVIHC35,NaN,05aug2012,22sep2013,413,14,04=Diaries Interview,25jan2013,1,2013,...,07=Group meeting,Outflow,12350.0,145.2941,0,NaN,NaN,NaN,5.689655,0.0

### Here I "cleaned" data for housing in excel. What can be extracted: if owned, number and value of additional property

In [42]:
df1 = pd.read_csv('../housing_conditions_ownership.csv')
dfh=df1[['hh_ids','owned','N', 'other_prop_or_shamba_value' ]]
dfh.head()

    hh_ids owned    N  other_prop_or_shamba_value
0  KNBOK31    no  NaN                         NaN
1  KNBOK01   yes  NaN                         NaN
2  KNBOK02   yes  NaN                         NaN
3  KNBOK04   yes  1.0                   1500000.0
4  KNBOK05   yes  NaN                         NaN

In [41]:
pd.merge(dfb, dfh, on = 'hh_ids', how='outer')

,hh_ids,unique_hhs,first_trx_date_hh,last_trx_date_hh,tot_hh_daysofobs,tot_hh_monthsofobs,interview_designation,int_date,int_month,int_year,...,trx_value_usd,ddd_gift,trx_inkind_units,trx_inkind_value_usd,trx_inkind_value_kes,trx_stdtime_mnths_hh_nr,acc_unexplained_trx,owned,N,other_prop_or_shamba_value
0,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,06=Cleaning interview,04oct2013,10.0,2013.0,...,1191.76500,0.0,NaN,NaN,NaN,13.379310,0.0,yes,NaN,NaN
1,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,04jun2013,6.0,2013.0,...,411.76470,0.0,NaN,NaN,NaN,8.931034,0.0,yes,NaN,NaN
2,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,06=Cleaning interview,04oct2013,10.0,2013.0,...,210.58820,0.0,NaN,NaN,NaN,13.379310,0.0,yes,NaN,NaN
3,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,03=Q3,02oct2012,10.0,2012.0,...,1035.29400,0.0,NaN,NaN,NaN,0.758621,0.0,yes,NaN,NaN
4,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,14nov2012,11.0,2012.0,...,31.76471,0.0,NaN,NaN,NaN,1.482759,0.0,yes,NaN,NaN
5,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,29jan2013,1.0,2013.0,...,23.52941,0.0,NaN,NaN,NaN,4.620690,0.0,yes,NaN,NaN
6,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,04jul2013,7.0,2013.0,...,47.05882,0.0,NaN,NaN,NaN,10.000000,0.0,yes,NaN,NaN
7,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,09apr2013,4.0,2013.0,...,20.58824,0.0,NaN,NaN,NaN,6.896552,0.0,yes,NaN,NaN
8,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,15jan2013,1.0,2013.0,...,25.88235,0.0,NaN,NaN,NaN,3.413793,0.0,yes,NaN,NaN
9,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,23jul2013,7.0,2013.0,...,132.35290,0.0,NaN,NaN,NaN,10.310340,0.0,yes,NaN,NaN
10,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,14nov2012,11.0,2012.0,...,31.76471,0.0,NaN,NaN,NaN,2.206897,0.0,yes,NaN,NaN
11,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,15jan2013,1.0,2013.0,...,47.05882,0.0,NaN,NaN,NaN,4.137931,0.0,yes,NaN,NaN
12,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,20aug2013,8.0,2013.0,...,132.35290,0.0,NaN,NaN,NaN,11.379310,0.0,yes,NaN,NaN
13,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,29jan2013,1.0,2013.0,...,23.52941,0.0,NaN,NaN,NaN,4.379310,0.0,yes,NaN,NaN
14,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,21may2013,5.0,2013.0,...,47.05882,0.0,NaN,NaN,NaN,8.310345,0.0,yes,NaN,NaN
15,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,23oct2012,10.0,2012.0,...,29.41176,0.0,NaN,NaN,NaN,1.241379,0.0,yes,NaN,NaN
16,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,14nov2012,11.0,2012.0,...,31.76471,0.0,NaN,NaN,NaN,1.724138,0.0,yes,NaN,NaN
17,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,27nov2012,11.0,2012.0,...,30.58824,0.0,NaN,NaN,NaN,2.448276,0.0,yes,NaN,NaN
18,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,09apr2013,4.0,2013.0,...,24.70588,0.0,NaN,NaN,NaN,6.655172,0.0,yes,NaN,NaN
19,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,18jun2013,6.0,2013.0,...,47.05882,0.0,NaN,NaN,NaN,9.482759,0.0,yes,NaN,NaN
20,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,19mar2013,3.0,2013.0,...,26.47059,0.0,NaN,NaN,NaN,6.413793,0.0,yes,NaN,NaN
21,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,18sep2013,9.0,2013.0,...,131.76470,0.0,NaN,NaN,NaN,12.551720,0.0,yes,NaN,NaN
22,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,27nov2012,11.0,2012.0,...,11.76471,0.0,NaN,NaN,NaN,2.620690,0.0,yes,NaN,NaN
23,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,07may2013,5.0,2013.0,...,71.76471,0.0,NaN,NaN,NaN,7.827586,0.0,yes,NaN,NaN
24,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,18dec2012,12.0,2012.0,...,25.88235,0.0,NaN,NaN,NaN,2.689655,0.0,yes,NaN,NaN
25,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,21may2013,5.0,2013.0,...,17.64706,0.0,NaN,NaN,NaN,8.310345,0.0,yes,NaN,NaN
26,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,18dec2012,12.0,2012.0,...,25.88235,0.0,NaN,NaN,NaN,3.172414,0.0,yes,NaN,NaN
27,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,14nov2012,11.0,2012.0,...,31.76471,0.0,NaN,NaN,NaN,1.965517,0.0,yes,NaN,NaN
28,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,19feb2013,2.0,2013.0,...,49.41177,0.0,NaN,NaN,NaN,5.344828,0.0,yes,NaN,NaN
29,KVIHK40,NaN,10sep2012,03oct2013,388.0,13.0,04=Diaries Interview,21may2013,5.0,2013.0,...,11.76471,0.0,NaN,NaN,NaN,8.344828,0.0,yes,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,KVIHC25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
701,KVIHC26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,1.0,99.0
702,KVIHC34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
703,KVIHK01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
704,KVIHK02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
705,KVIHK05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
706,KVIHK06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,2.0,400000.0
707,KVIHK07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
708,KVIHK10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
709,KVIHK11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,2.0,900000.0
710,KVIHK13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
711,KVIHK15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
712,KVIHK16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
713,KVIHK17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,1.0,500000.0
714,KVIHK18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
715,KVIHK19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,2.0,400000.0
716,KVIHK21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
717,KVIHK22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
718,KVIHK23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,1.0,400000.0
719,KVIHK24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
720,KVIHK26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
721,KVIHK29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,2.0,1750000.0
722,KVIHK31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
723,KVIHK32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
724,KNBOK36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
725,KNBOK38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN
726,KNBOK39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,1.0,150000.0
727,KNBOK40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,1.0,300000.0
728,KNBOK41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,2.0,250000.0
729,KNBOK42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN