In [1]:
import os
import pandas as pd 
import glob
import random 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [20]:
pd.set_option('display.max_columns',200)
pd.set_option('display.max_rows',680)

## Determine how quickly someone pays back their one time loans, separated into their respective categories:

In [4]:
trx = pd.read_csv('../diaries_transactions_all.csv', low_memory = False)

In [5]:
liability_trx = trx.loc[trx['account_bsheet_desig'] == "Liability"]
liability_trx.shape

(23078, 58)

In [7]:
liability_trx.trx_family_code.value_counts()

INFP2P     14755
SUPPCRD     4050
FRMLN       1429
INFGRP      1377
ARREARS     1058
ADVANCE      280
EMPLN        111
PAWN          16
OTHER          2
Name: trx_family_code, dtype: int64

In [8]:
liability_trx.trx_family_desc.value_counts()

Informal P2P                              14755
Supplier credit                            4050
Formal loan                                1429
Informal group                             1377
Arrears owed to or owed by respondents     1058
Advance                                     280
Loan from employer                          111
Pawning assets                               16
Other                                         2
Name: trx_family_desc, dtype: int64

In [9]:
liability_trx.trx_type_desc.value_counts()

Informal credit at a store                   12022
Okoa Jahazi                                   2973
Friends and family: Borrowing                 2073
Borrowing from an informal Group              1377
Supplier credit                               1077
Arrears owed by respondents                   1058
Act as money guard                             449
Individual Business or Agriculture Loan        442
Consumer/ personal loan (not payday loan)      324
Wage advance                                   280
Joint liability loan                           265
Moneylender or Shylock Borrowing               211
Hire Purchase                                  148
Loan from employer                             111
School Fees Loan                               107
M-SHWARI Loan                                  105
Group Enterprise Loan                           28
Pawning assets                                  16
Payday loan                                      5
Credit card (including store card)               3
Bail Bond                                        2
Student loan                                     2
Name: trx_type_desc, dtype: int64

In [13]:
friends_family_borrowing_df = liability_trx.loc[liability_trx['trx_type_desc']=="Friends and family: Borrowing"]

In [15]:
len(friends_family_borrowing.account_ids.unique())

605

In [16]:
friends_family_borrowing.shape

(2073, 58)

In [23]:
friends_family_borrowing.account_ids.value_counts()

57137225366300000     28
57136574022700000     19
60136177195600000     18
61135780595200000     15
60135918356600000     15
89136060846900000     14
63135935605300000     11
58134709702500000     10
89137593971300000     10
61135305343000000      9
62136429071700000      9
65134701388900000      9
60135196617100000      9
65137213659900000      9
57136390521500000      9
61136004358800000      9
62137275757000000      8
56135281752300000      8
60134848077100000      8
79134925908800000      8
57135784508700000      7
84136869241900000      7
57137223327200000      7
63135513232500000      7
57134822995600000      7
62134702499000000      7
111137122807100000     7
57136505913700000      7
105136686050400000     7
89136747391600000      7
57136607675600000      7
57136138765200000      7
61135901711600000      6
61135029606000000      6
57135376160800000      6
89136747336400000      6
89136404360000000      6
60135373653400000      6
65136428308800000      6
62135953702000000      6
61136335645000000      6
57134822921000000      6
60134795055500000      6
59134847814700000      6
105136851021100000     6
65134761295400000      6
60135774661000000      6
57136607619700000      6
58136393590400000      6
89137092188700000      6
65135817454500000      6
61135780914500000      6
61135529431100000      6
50135307022400000      5
60136541481700000      5
60136868060300000      5
62135979874800000      5
60135431218900000      5
63136117543300000      5
61136075236600000      5
57135417899800000      5
89136307152000000      5
63134752116200000      5
57137187279000000      5
58134761873000000      5
105137619268700000     5
61135367284400000      5
62134858732800000      5
62136415917000000      5
57137244051800000      5
61134830092000000      5
50135515017100000      5
62134726852400000      5
89135875280500000      5
61135730374600000      5
57137704820400000      5
63134823714200000      5
59136005961700000      5
108137697519800000     5
60135037092700000      5
61136336195000000      5
62135944664900000      5
57134614315600000      5
63137784226500000      5
89136318373800000      5
65134795283400000      5
57137465103100000      5
60134795353300000      5
57135920498600000      5
57136472559400000      5
61135978182200000      5
57137707753700000      5
59135867049500000      5
65137153487600000      5
61134882997100000      5
57135875605000000      5
59135900876800000      5
65136359989100000      5
65136480775500000      5
57135245550300000      5
61135297155800000      4
63137706553400000      4
84136514267200000      4
57137326394200000      4
61134822378600000      4
105137178633000000     4
89137464915700000      4
57134702741000000      4
65134786828600000      4
65136670292700000      4
63136316670800000      4
79134847304300000      4
57135997664300000      4
63136393689200000      4
57136756570100000      4
57134701947500000      4
62134745343300000      4
61134925066900000      4
61135375552700000      4
60135912009700000      4
57134676088100000      4
65134753088900000      4
61136071356000000      4
89137319463000000      4
60134847736800000      4
108137093557300000     4
61135797521800000      4
57134719497400000      4
60135456285000000      4
60134734410200000      4
56134746393900000      4
60135875217200000      4
63134735712400000      4
34136670007100000      4
112137860640300000     4
57137083794400000      4
84136869288300000      4
108137827087300000     4
61135530794100000      4
105136781003300000     4
62134734874700000      4
60136101520400000      4
112137860675900000     4
59135892070300000      4
61136074146000000      4
63134823743500000      4
61135250223400000      4
59137010685800000      4
79134925826800000      4
57135910764300000      4
105137940000000000     4
58136393504100000      4
57135280530200000      4
61136523215700000      4
60135282260000000      4
62134821573500000      4
59134847836800000      4
63137462219700000      4
105137638498100000     4
57137665019500000      4
60136798779200000      4
57136612419800000      4
50135729622700000      4
61135479505200000      4
62137718570800000      4
62134726143600000      4
57136827549200000      4
61135390372500000      4
89137832443000000      4
61136507829000000      4
61134745539100000      4
60135900895400000      4
50135823848600000      4
62134700719700000      4
89137591184100000      4
89136005536900000      4
62135961796200000      4
61135345059600000      4
59135158340400000      4
50138069433200000      3
57135988169700000      3
57137482234100000      3
89135946068600000      3
60136411459900000      3
59137013714200000      3
57136939296600000      3
50138069339200000      3
61135342083300000      3
63137465397300000      3
57137085857700000      3
60137223317200000      3
57137223356600000      3
65136963462200000      3
89137516688300000      3
89137162126300000      3
63137837104900000      3
89136774178400000      3
59136557969100000      3
57135988138600000      3
105137422215200000     3
61135972359900000      3
61135221208000000      3
57137083271100000      3
63137622498500000      3
62138087095500000      3
112137842570700000     3
57135149434500000      3
105136652292900000     3
57134856578500000      3
105137940040500000     3
105136625622100000     3
60134725801400000      3
34138313407600000      3
61134734993200000      3
50135288469600000      3
63137017786700000      3
89136056990700000      3
105136773258700000     3
62138172353000000      3
57137595918300000      3
57136617744800000      3
61135011185100000      3
65137092606900000      3
89136130198800000      3
57137213372600000      3
60137135371000000      3
57137155231300000      3
60137359808600000      3
57137645093200000      3
89135887391000000      3
105137706953500000     3
57136471177300000      3
89137146576200000      3
58134744031100000      3
62137707909800000      3
63137351696800000      3
79135029094800000      3
60137214593400000      3
62137387393300000      3
60136742570000000      3
59136967517300000      3
62135849350200000      3
57137308008700000      3
61135297426400000      3
65137523772500000      3
111137282579200000     3
60135456332400000      3
105137032077200000     3
50135823857900000      3
63136283110800000      3
89137032063800000      3
63137653875100000      3
105137743375700000     3
65137153679200000      3
50138069382700000      3
105136937638500000     3
62135901637000000      3
61135012467200000      3
63135428281400000      3
60135566497700000      3
62138243269200000      3
60137888917800000      3
112137894607400000     3
105137525489200000     3
59136790667500000      3
61135344941600000      3
57137467234400000      3
63136479549300000      3
56135314065000000      3
65137360787600000      3
105137743333800000     3
105137940070700000     3
63137776682900000      3
63135428589900000      3
57137571728500000      3
57138043579100000      3
61135479446100000      3
57137281998000000      3
60137342946100000      3
57134796192500000      3
63137284898000000      3
63135239911800000      3
61134761289100000      3
79134925858100000      3
57135970556700000      3
59136633268200000      3
57135384785200000      3
63137655721800000      3
105137542122500000     3
112137346957600000     3
63137005793200000      3
62134727320400000      3
65136885395300000      3
57135945214300000      3
59134794889400000      3
57135861293900000      3
59134855681000000      3
60134700222900000      3
89138319558400000      3
105137862516300000     3
59136790639000000      3
61134727282000000      3
57136827284000000      3
111137338240800000     3
59135418170100000      3
65136487395200000      3
63135109308100000      3
50136860043200000      3
61136764423100000      3
50135823838200000      3
89137396226900000      3
57135937093400000      3
89137750804300000      3
89135935720300000      3
79135029208800000      3
112138303243500000     3
105136661477100000     3
65134761541100000      3
65137523812200000      3
63134855976700000      3
62136342877500000      3
63136893411900000      3
105137758678500000     3
56135427073300000      3
60137570414300000      3
84136851377600000      3
60136411489200000      3
58134702573000000      3
89137591032200000      3
57136946979100000      3
89136480481700000      3
57137162573900000      3
60137585235500000      3
62134804773500000      3
89137162086900000      3
63134796726600000      3
62136601265300000      3
57136877646600000      3
50136852173400000      3
63135935649600000      3
105137992124700000     3
61135055971200000      3
57136109011900000      3
60136715715500000      3
63137160870000000      3
50135515030300000      3
65137058079200000      3
50135816583200000      3
89137162106000000      3
57136298280000000      3
60136411420900000      3
60135912023500000      3
60137448419700000      3
57134796005600000      3
79134847883300000      3
62136413354600000      3
105137637052200000     3
60135235701300000      3
63136749696600000      3
105136937269800000     3
89136818225700000      3
105137378009900000     3
63137327372100000      3
105136781588300000     3
61134737913700000      3
105137291881300000     3
60134846625100000      3
61134728589400000      3
89137578416400000      3
63136725293400000      3
60137636051100000      3
57134926252300000      3
50137243579600000      3
89137995323700000      3
63135132564900000      3
63134823696100000      3
65136368389400000      3
57137669413000000      3
89137033513200000      3
57134796164500000      3
63135150383300000      3
61134788714200000      3
62135348953200000      3
63136419745400000      3
89135996179900000      3
62135849616700000      3
60137390793800000      3
60136947995400000      3
56135219351900000      3
61136421344400000      3
105137110893600000     3
59136539784600000      3
57135443712800000      3
57135460106800000      3
89136626903900000      3
111137260498400000     3
65137576328500000      3
63137289758600000      3
60137057227600000      3
61135038536700000      3
89137032036400000      3
112137148620400000     3
63137637231000000      3
61135012577400000      3
79135029162000000      3
57134682920900000      3
79134847276300000      3
57136272901000000      3
105137414952600000     3
105136801245500000     3
89137706153900000      3
105136937296500000     3
105137386574500000     3
61135573258800000      3
89137581619600000      3
89138035657700000      3
59136634966100000      3
57137076641000000      3
60137753993100000      3
60135773633900000      3
57137700880800000      3
63135162597000000      3
57136058425900000      3
112137421189900000     3
112137140977800000     3
61135971126000000      3
57136308837800000      3
89135733237900000      3
63138260435400000      3
63135523008000000      3
61134881050500000      3
63136316745500000      3
62134769863600000      3
89137057749800000      3
57136763658400000      3
79135029136300000      3
61136188768400000      3
63135523073800000      3
65137524453000000      3
89137525820000000      3
60134710639900000      3
60136233650600000      3
61135576049400000      3
105136574599800000     3
57137749404400000      3
60136432538900000      3
63134745062100000      3
89137049065100000      3
60135853569900000      3
63137748625100000      3
59135921229600000      3
65136937168900000      3
105137312375300000     3
60134734683000000      3
57135832243700000      2
60137213163200000      2
57134795957700000      2
112137118814000000     2
89136516084600000      2
57135340095900000      2
79134832000000000      2
50136729724400000      2
65136379903700000      2
111137282581900000     2
112137463964500000     2
60136449070000000      2
59137481626000000      2
61135946354400000      2
89135946111400000      2
105136938064800000     2
57137766942400000      2
63134762500500000      2
65137653786300000      2
60137942425900000      2
57136877129600000      2
60135939579700000      2
61135780962400000      2
61134787763500000      2
61135781031900000      2
89136316620900000      2
57137817733100000      2
65137930163300000      2
79134917397800000      2
62135125446300000      2
57137069613100000      2
105137576928200000     2
105136938253200000     2
60137446253500000      2
79134900832500000      2
63137776408600000      2
105136801272100000     2
108137416086400000     2
57135936974600000      2
89137024084000000      2
59137584993200000      2
59136385078800000      2
57134649653900000      2
60138270654600000      2
61135072444900000      2
60135902151300000      2
105138011320800000     2
59134795856400000      2
112137430176200000     2
65138008005400000      2
60134727448800000      2
112137708681400000     2
65135299392500000      2
112137592700400000     2
57138028119400000      2
61136074663200000      2
108136919734900000     2
56135058127000000      2
79134847334700000      2
56135953015000000      2
57134719012600000      2
60138009492300000      2
57135591518400000      2
89137033396300000      2
61134779738600000      2
60134761522600000      2
105138001256100000     2
89136644791500000      2
105136817210500000     2
60134692324500000      2
62137878881000000      2
63135023941500000      2
59137481562800000      2
60137551080800000      2
63134771441100000      2
60137930789900000      2
63134773687500000      2
60137969335100000      2
57134994043500000      2
105136738868100000     2
84137387783900000      2
112137715178600000     2
61134881028800000      2
58134743714300000      2
60137528081400000      2
61134925987500000      2
60137096698000000      2
63137692650400000      2
105137895695500000     2
89138129793600000      2
61134822985000000      2
89138355781400000      2
65137118514300000      2
112137566536600000     2
112137964060300000     2
89136792195800000      2
60135373621900000      2
59136668956900000      2
61135996665000000      2
65135399590100000      2
57137768378400000      2
61135375534800000      1
59136376471900000      1
61136361185100000      1
61135730355300000      1
57136390495300000      1
61135375545100000      1
57135417297800000      1
58134710013000000      1
59134692335200000      1
63136693531200000      1
60137519164500000      1
61135912092100000      1
57136222996200000      1
89138251838000000      1
57134976734900000      1
89137836028700000      1
112138200193100000     1
62138070678500000      1
112137118310300000     1
57134615936900000      1
57136910894300000      1
61135018720800000      1
112137153237600000     1
61135375548500000      1
50135237201800000      1
89136602534000000      1
112137140409300000     1
57136342821100000      1
57134804084300000      1
58134797408600000      1
89136609773200000      1
50135237176900000      1
60134734882100000      1
57135427347800000      1
112137266202700000     1
79135073072300000      1
89136602520600000      1
59137524198200000      1
63136693553000000      1
59135530841600000      1
57137828400900000      1
112137833390300000     1
63136693579500000      1
112137270085000000     1
57136471645300000      1
57136909482700000      1
61135530364200000      1
61134770551400000      1
89136602503600000      1
61135531048100000      1
Name: account_ids, dtype: int64

### FF borrowing ranges from 1 - 28 transactions

In [24]:
### what one of them looks like that has 1 transaction:

In [21]:
friends_family_borrowing.loc[friends_family_borrowing['account_ids']=='61134770551400000']

,hh_ids,unique_hhs,first_trx_date_hh,last_trx_date_hh,tot_hh_daysofobs,tot_hh_monthsofobs,interview_designation,int_date,int_month,int_year,int_yr_mo,first_int_date,account_ids,unique_accnts,m_ids_owner,unique_hm_owner,account_bsheet_desig,account_startclose_balance,account_formal,account_liquid,first_trx_date_acc,last_trx_date_acc,tot_acc_daysofobs,tot_acc_monthsofobs,trx_id,m_ids_trx,trx_date,trx_month,trx_year,trx_yr_mo,trx_dq_round,trx_stdtime_days_hh,trx_stdtime_mnths_hh,trx_stdtime_days_acc,trx_stdtime_mnths_acc,trx_class_code,trx_class_desc,trx_family_code,trx_family_desc,trx_type_code,trx_type_desc,trx_prx_purpose,trx_prx_purpose_fd,trx_fee,trx_bsheet_direction,trx_mode_code,trx_mode_desc,trx_place_incommunity,trx_distance_km,trx_outlet,trx_direction,trx_value_kes,trx_value_usd,ddd_gift,trx_inkind_units,trx_inkind_value_usd,trx_inkind_value_kes,trx_stdtime_mnths_hh_nr
11736,KMOMK03,NaN,07sep2012,25oct2013,413,14,03=Q3,29sep2012,9,2012,2012_09,01sep2012,61134770551400000,1.0,61134406243400000,NaN,Liability,Start,Informal,NaN,29sep2012,29sep2012,0,0,61134891914800000,61134406243400000,29sep2012,9,2012,2012_09,1.0,22,0,0,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,1. Starting balance (today),NaN,0.0,Increase,18.0,STARTING BALANCE,NaN,NaN,NaN,NaN,8000.0,94.11765,0,NaN,NaN,NaN,0.758621

In [25]:
friends_family_borrowing.loc[friends_family_borrowing['account_ids']=='57136574022700000']

,hh_ids,unique_hhs,first_trx_date_hh,last_trx_date_hh,tot_hh_daysofobs,tot_hh_monthsofobs,interview_designation,int_date,int_month,int_year,int_yr_mo,first_int_date,account_ids,unique_accnts,m_ids_owner,unique_hm_owner,account_bsheet_desig,account_startclose_balance,account_formal,account_liquid,first_trx_date_acc,last_trx_date_acc,tot_acc_daysofobs,tot_acc_monthsofobs,trx_id,m_ids_trx,trx_date,trx_month,trx_year,trx_yr_mo,trx_dq_round,trx_stdtime_days_hh,trx_stdtime_mnths_hh,trx_stdtime_days_acc,trx_stdtime_mnths_acc,trx_class_code,trx_class_desc,trx_family_code,trx_family_desc,trx_type_code,trx_type_desc,trx_prx_purpose,trx_prx_purpose_fd,trx_fee,trx_bsheet_direction,trx_mode_code,trx_mode_desc,trx_place_incommunity,trx_distance_km,trx_outlet,trx_direction,trx_value_kes,trx_value_usd,ddd_gift,trx_inkind_units,trx_inkind_value_usd,trx_inkind_value_kes,trx_stdtime_mnths_hh_nr
1777,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,22may2013,5,2013,2013_05,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136919444100000,57134433115100000,29apr2013,4,2013,2013_04,12.0,237,8,21,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,NaN,NaN,NaN,Outflow,300.0,3.529412,0,NaN,NaN,NaN,8.172414
12097,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,26sep2013,9,2013,2013_09,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,Close,Informal,NaN,08apr2013,26sep2013,171,5,57138016725200000,57134433115100000,26sep2013,9,2013,2013_09,18.0,387,13,171,5,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,7. Closing Balance--End of last DQ,NaN,0.0,NaN,19.0,CLOSING BALANCE,NaN,NaN,NaN,NaN,0.0,0.000000,0,NaN,NaN,NaN,13.344830
16611,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,12apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57137749237100000,57134433115100000,08apr2013,4,2013,2013_04,10.0,216,7,0,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,5. Interest accruing,NaN,0.0,Increase,16.0,Automatic,NaN,NaN,NaN,NaN,2000.0,23.529410,0,NaN,NaN,NaN,7.448276
473350,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,22may2013,5,2013,2013_05,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136937271100000,57134433115100000,25apr2013,4,2013,2013_04,12.0,233,8,17,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,4.0,"Mobile money transfer (M-PESA, Airtel Money, O...",0.0,2.281859,04=Mobile phone only,Outflow,1200.0,14.117650,0,NaN,NaN,NaN,8.034483
473354,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,22may2013,5,2013,2013_05,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136937263800000,57134433115100000,01may2013,5,2013,2013_05,12.0,239,8,23,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,4.0,"Mobile money transfer (M-PESA, Airtel Money, O...",0.0,2.281859,04=Mobile phone only,Outflow,1600.0,18.823530,0,NaN,NaN,NaN,8.241380
473553,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677732700000,57134433115100000,18apr2013,4,2013,2013_04,11.0,226,7,10,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.793103
473724,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677732700000,57134433115100000,20apr2013,4,2013,2013_04,11.0,228,7,12,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.862069
474120,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677728500000,57134433115100000,12apr2013,4,2013,2013_04,11.0,220,7,4,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.586207
474136,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677732700000,57134433115100000,21apr2013,4,2013,2013_04,11.0,229,7,13,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.896552
474908,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677732700000,57134433115100000,23apr2013,4,2013,2013_04,11.0,231,7,15,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.965517
474910,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,12apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136574066800000,57134433115100000,10apr2013,4,2013,2013_04,10.0,218,7,2,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.517241
475029,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677732700000,57134433115100000,22apr2013,4,2013,2013_04,11.0,230,7,14,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.931035
475575,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,12apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136574096300000,57134433115100000,09apr2013,4,2013,2013_04,10.0,217,7,1,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.482759
475990,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677732700000,57134433115100000,19apr2013,4,2013,2013_04,11.0,227,7,11,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.827586
476332,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677732700000,57134433115100000,13apr2013,4,2013,2013_04,11.0,221,7,5,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.620690
476338,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,24apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136677736300000,57134433115100000,14apr2013,4,2013,2013_04,11.0,222,7,6,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,1600.0,18.823530,0,NaN,NaN,NaN,7.655172
476999,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,12apr2013,4,2013,2013_04,21aug2012,57136574022700000,1.0,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136574062700000,57134433115100000,08apr2013,4,2013,2013_04,10.0,216,7,0,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,2. New borrowing,New borrowing on financial liability,0.0,Increase,1.0,Cash,0.0,2.281859,13=Private individual or household,Inflow,10000.0,117.647100,0,NaN,NaN,NaN,7.448276
477084,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,22may2013,5,2013,2013_05,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136937279300000,57134433115100000,02may2013,5,2013,2013_05,12.0,240,8,24,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,4.0,"Mobile money transfer (M-PESA, Airtel Money, O...",0.0,2.281859,04=Mobile phone only,Outflow,2900.0,34.117650,0,NaN,NaN,NaN,8.275862
477206,KMOMM18,NaN,04sep2012,28sep2013,389,13,04=Diaries Interview,12apr2013,4,2013,2013_04,21aug2012,57136574022700000,NaN,57134433115100000,NaN,Liability,NaN,Informal,NaN,08apr2013,26sep2013,171,5,57136574069400000,57134433115100000,11apr2013,4,2013,2013_04,10.0,219,7,3,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,0.0,2.281859,13=Private individual or household,Outflow,400.0,4.705883,0,NaN,NaN,NaN,7.551724

In [29]:
x = friends_family_borrowing.loc[friends_family_borrowing['account_ids']=='63134735712400000'].copy()

In [30]:
x.sort_values("trx_stdtime_days_acc", inplace=True)

In [31]:
x

,hh_ids,unique_hhs,first_trx_date_hh,last_trx_date_hh,tot_hh_daysofobs,tot_hh_monthsofobs,interview_designation,int_date,int_month,int_year,int_yr_mo,first_int_date,account_ids,unique_accnts,m_ids_owner,unique_hm_owner,account_bsheet_desig,account_startclose_balance,account_formal,account_liquid,first_trx_date_acc,last_trx_date_acc,tot_acc_daysofobs,tot_acc_monthsofobs,trx_id,m_ids_trx,trx_date,trx_month,trx_year,trx_yr_mo,trx_dq_round,trx_stdtime_days_hh,trx_stdtime_mnths_hh,trx_stdtime_days_acc,trx_stdtime_mnths_acc,trx_class_code,trx_class_desc,trx_family_code,trx_family_desc,trx_type_code,trx_type_desc,trx_prx_purpose,trx_prx_purpose_fd,trx_fee,trx_bsheet_direction,trx_mode_code,trx_mode_desc,trx_place_incommunity,trx_distance_km,trx_outlet,trx_direction,trx_value_kes,trx_value_usd,ddd_gift,trx_inkind_units,trx_inkind_value_usd,trx_inkind_value_kes,trx_stdtime_mnths_hh_nr
6361,KMAKE29,NaN,14sep2012,02oct2013,383,13,03=Q3,25sep2012,9,2012,2012_09,28aug2012,63134735712400000,1.0,63134363763200000,NaN,Liability,Start,Informal,NaN,25sep2012,02oct2013,372,12,63134860552600000,63134363763200000,25sep2012,9,2012,2012_09,1.0,11,0,0,0,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,1. Starting balance (today),NaN,0.0,Increase,18.0,STARTING BALANCE,NaN,NaN,NaN,NaN,5000.0,58.82353,0,NaN,NaN,NaN,0.379310
414307,KMAKE29,NaN,14sep2012,02oct2013,383,13,04=Diaries Interview,20nov2012,11,2012,2012_11,28aug2012,63134735712400000,NaN,63134363763200000,NaN,Liability,NaN,Informal,NaN,25sep2012,02oct2013,372,12,63135339948400000,63134363763200000,09nov2012,11,2012,2012_11,4.0,56,1,45,1,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,1.0,0.0,13=Private individual or household,Outflow,3000.0,35.29412,0,NaN,NaN,NaN,1.931034
41597,KMAKE29,NaN,14sep2012,02oct2013,383,13,04=Diaries Interview,07jan2013,1,2013,2013_01,28aug2012,63134735712400000,NaN,63134363763200000,NaN,Liability,NaN,Informal,NaN,25sep2012,02oct2013,372,12,63135815788100000,63134363763200000,02jan2013,1,2013,2013_01,5.0,110,3,99,3,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,3. Payments,Repayment on financial liability,0.0,Decrease,1.0,Cash,1.0,0.0,13=Private individual or household,Outflow,2000.0,23.52941,0,NaN,NaN,NaN,3.793103
4382,KMAKE29,NaN,14sep2012,02oct2013,383,13,06=Cleaning interview,02oct2013,10,2013,2013_10,28aug2012,63134735712400000,NaN,63134363763200000,NaN,Liability,Close,Informal,NaN,25sep2012,02oct2013,372,12,105140418771000000,63134363763200000,02oct2013,10,2013,2013_10,21.0,383,13,372,12,findev,"Borrowing, lending, savings or insurance media...",INFP2P,Informal P2P,2752,Friends and family: Borrowing,7. Closing Balance--End of last DQ,NaN,0.0,NaN,19.0,CLOSING BALANCE,NaN,NaN,NaN,NaN,0.0,0.00000,0,NaN,NaN,NaN,13.206900